gateways:
    local:
        connection:
            type: duckdb
            database: db.db
    external:
        connection:
            type: duckdb
            database: external_data/external_source.db

default_gateway: local

model_defaults:
    dialect: duckdb
