-- Table of revenue generated by each waiter by day.
MODEL (
  name sushi.waiter_revenue_by_day,
  kind incremental_by_time_range (
    time_column (ds, '%Y-%m-%d'),
  ),
  cron '@daily',
  start '2023-01-01',
  grain (waiter_id, ds)
);

SELECT
  o.waiter_id::INT AS waiter_id, -- Waiter id
  SUM(oi.quantity * i.price)::DOUBLE AS revenue, -- Revenue from orders taken by this waiter
  o.ds::TEXT AS ds -- Order date
FROM raw.orders AS o
LEFT JOIN raw.order_items AS oi
  ON o.id = oi.order_id AND o.ds = oi.ds
LEFT JOIN raw.items AS i
  ON oi.item_id = i.id AND oi.ds = i.ds
WHERE
  o.ds BETWEEN @start_ds AND @end_ds
GROUP BY
  o.waiter_id,
  o.ds
