/*
  Incremental table of revenue generated by each waiter by day.
*/
MODEL (
  name sushimoderate.waiter_revenue_by_day,
  kind INCREMENTAL_BY_TIME_RANGE (
    time_column (ds, '%Y-%m-%d'),
  ),
  cron '@daily',
  start '2023-01-01',
  grains [waiter_id, ds],
  audits (
    NUMBER_OF_ROWS(threshold=0)
  ),
);

SELECT
  o.waiter_id::INT AS waiter_id, /* Waiter id */
  SUM(oi.quantity * i.price)::DOUBLE AS revenue, /* Revenue from orders taken by waiter on day */
  o.ds::TEXT AS ds /* Order date */
FROM sushimoderate.orders AS o
LEFT JOIN sushimoderate.order_items AS oi
  ON o.id = oi.order_id AND o.ds = oi.ds
LEFT JOIN sushimoderate.items AS i
  ON oi.item_id = i.id AND oi.ds = i.ds
WHERE
  o.ds BETWEEN @start_ds AND @end_ds
GROUP BY
  o.waiter_id,
  o.ds;
